# Build and deploy: netlify deploy --build --prod
# Site ID: 012beee7-f0b1-41e9-9ca3-49fff7edd954
# NEXT_FORCE_EDGE_IMAGES=true

#[[plugins]]
#package = "@netlify/plugin-nextjs"

[build]
command = "pnpm build"
publish = ".next"