# Build and deploy: netlify deploy --build --prod

[[plugins]]
package = "@netlify/plugin-nextjs"

[build]
command = "pnpm run build"
publish = ".next"

[[redirects]]
from = "/_next/static/*"
to = "/static/:splat"
status = 301
force = true